// MANTRA

#ifndef _MANTRA_NETWORK_COMMON_H
#define _MANTRA_NETWORK_COMMON_H

#define DEFAULT_GAME_SERVER_IP   "localhost"
#define DEFAULT_GAME_SERVER_PORT 40404
#define DEFAULT_MASTER_SERVER_IP "localhost"
#define DEFAULT_MASTER_SERVER    40403

typedef enum{
    NFILE_NOP=0,
    NFILE_ACK,
    NFILE_ABORT,
    NFILE_START,
    NFILE_START_OK,
    NFILE_DATA,
    NFILE_DATA_OK,
    NFILE_DATA_RESEND,
    NFILE_EOF,
    NFILE_EOF_RESEND,
    NFILE_RESUME,
    NFILE_RESUME_OK,
    NFILE_RESUME_CANT,
    NFILE_ERROR

} tfilexfer;
typedef enum{

    NM_NOMESSAGE = 1,
    NM_NOP,

    NM_FUNCTION,

    NM_LOGIN_REQUEST,
    NM_LOGIN_REQUEST_REPLY,
    NM_LOGOUT,

    NM_HEARTBEAT,
    NM_HEARTBEAT_REQUEST,

    NM_MESSAGE,

    NM_MOVEPLAYER,

    NM_CREATE_CHARACTER,
    NM_DELETE_CHARACTER,
    NM_MODIFY_CHARACTER,
    NM_RETRIEVECHARS,
    NM_RETRIEVECHARINFO,
    NM_GETINVENTORY,

    NM_CLIENT_SHUTDOWN,
    NM_OTHER_CLIENT_SHUTDOWN,

    NM_CHARACTER_STATUS,

    NM_FILE_XFER,
    NM_MANTRA_DOWNLOAD,
    NM_MANTRA_UPLOAD,

    NM_PING,

    NM_PROMPT,

    NM_GET_SERVER_INFO,
    NM_PUT_SERVER_INFO,
    NM_GET_SERVER_LIST,
    NM_MASTER_TO_GAME,

    NM_GUI,
    NM_GUI_CALLBACK,

} tNetmsg;

typedef enum{
    NF_CHAT_JOIN,
    NF_CHAT_LEAVE,
    NF_CHAT_WHO,


} tNetfunc;

#endif//_MANTRA_NETWORK_COMMON_H
