// EMBER

#ifndef _EMBER_GAME_SERVER_ENUM_H
#define _EMBER_GAME_SERVER_ENUM_H

typedef enum{
    NETMSG_NOMESSAGE = 1,
    NETMSG_NOP,
    NETMSG_LOGIN_REQUEST,
    NETMSG_LOGIN_REQUEST_REPLY,
    NETMSG_LOGOUT,
    NETMSG_SYSTEMMSG,
    NETMSG_LOCALCHAT,
    NETMSG_VIS_UPDATE,
    NETMSG_VIS_REMOVE,
    NETMSG_MOVEPLAYER,
    NETMSG_CREATE_CHARACTER,
    NETMSG_MODIFY_CHARACTER,
    NETMSG_RETRIEVECHARS,
    NETMSG_RETRIEVECHARINFO,
    NETMSG_GETINVENTORY,
    NETMSG_CHANGETILE,
    NETMSG_CHANGEOBJECT,
    NETMSG_CLIENTSHUTDOWN,
    NETMSG_DELETE_CHARACTER,
    NETMSG_GENERIC_MSG,
    NETMSG_SET_TILE,
    NETMSG_SET_OBJECT,
    NETMSG_CHANGE_MODE,
    NETMSG_MODIFY_MAP,
    NETMSG_SET_VERTEX,
    NETMSG_HEARTBEAT,
    NETMSG_HEARTBEAT_REQUEST,
    NETMSG_CHAR_STATUS,
    NETMSG_EMBER__DOWNLOAD,
    NETMSG_EMBER__UPLOAD,
    NETMSG_PING,
    NETMSG_PROMPT,
    NETMSG_FVM,
    NETMSG_SERVER_INFO,
    NETMSG_PUT_SERVER_INFO,
    NETMSG_GET_SERVER_LIST,
    NETMSG_MASTER_TO_GAME,
    NETMSG_GUI,
	NETMSG_GUI_COMMAND,
    NETMSG_GET_LOGIN_PROGRAM,
	NETMSG_SERVERINFORMATION,
	NETMSG_FILE_XFER,


} tNetmsg;

#endif//_EMBER_GAME_SERVER_ENUM_H
