.PHONY: clean All

All:
	@echo "----------Building project:[ ms - Debug ]----------"
	@"$(MAKE)" -f  "ms.mk"
clean:
	@echo "----------Cleaning project:[ ms - Debug ]----------"
	@"$(MAKE)" -f  "ms.mk" clean
